name: Lint and Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Jetzt können wir den Linter losschicken.
      - name: Lint
        run: |
          flake8

      # Jetzt können wir die Tests ausführen.
      - name: Test all the Things
        run: |
          pytest --cov=backmeup tests/